# Generated by Django 5.0.6 on 2024-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("to_do", "To Do"), ("cancel", "Cancel")],
                default="to_do",
                max_length=10,
            ),
        ),
    ]
