# Generated by Django 5.0.6 on 2024-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="prioritization",
            field=models.CharField(
                choices=[
                    ("must_have", "Must Have"),
                    ("should_have", "Should Have"),
                    ("could_have", "Could Have"),
                    ("will_not_have", "Will Not Have"),
                ],
                default="must_have",
                max_length=15,
            ),
        ),
    ]
