# Generated by Django 5.0.6 on 2024-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_task_prioritization"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="challenge",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="lesson_learned",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="risk_management",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To Do"),
                    ("doing", "Doing"),
                    ("done", "Done"),
                    ("cancel", "Cancel"),
                ],
                default="to_do",
                max_length=10,
            ),
        ),
    ]
