# Generated by Django 5.0.6 on 2024-07-24 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_task_challenge_task_lesson_learned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="task",
            name="lesson_learned",
        ),
        migrations.RemoveField(
            model_name="task",
            name="risk_management",
        ),
    ]
