# Generated by Django 5.0.6 on 2024-07-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_remove_task_challenge_remove_task_lesson_learned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="risk_management",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
