# Generated by Django 5.0.6 on 2024-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_task_risk_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="challenges",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
