# Generated by Django 5.0.6 on 2024-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_task_challenges"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="lesson_learned",
            field=models.TextField(blank=True, null=True),
        ),
    ]
