# Generated by Django 5.0.6 on 2024-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_task_lesson_learned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="prioritization",
        ),
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.CharField(
                choices=[
                    ("Sprint 1", "Sprint 1"),
                    ("Sprint 2", "Sprint 2"),
                    ("Sprint 3", "Sprint 3"),
                    ("Sprint 4", "Sprint 4"),
                ],
                default="Sprint 1",
                max_length=15,
            ),
        ),
    ]
