# Generated by Django 5.0.6 on 2024-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_remove_task_prioritization_task_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sprint",
            field=models.CharField(
                choices=[("S1", "S1"), ("S2", "S2"), ("S3", "S3"), ("S4", "S4")],
                default="S1",
                max_length=15,
            ),
        ),
    ]
