# Generated by Django 5.0.6 on 2025-08-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_task_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                help_text="This ticket cannot complete until the selected ticket is done.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="pages.task",
            ),
        ),
    ]
