# Generated by Django 5.0.6 on 2024-06-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="semester",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
