# Generated by Django 5.0.6 on 2024-07-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="project_mentor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="project_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="repo_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
